In [9]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
import networkx as nx
import icecream as ic

In [18]:
ROOT_PATH = '/Users/wolffjoa/Library/CloudStorage/OneDrive-mh-hannover.de/data/epigenetic-graph-analyzer'
graph_path = os.path.join(ROOT_PATH, 'FMI_data/MD_data_graph.graphml')
partition_path = os.path.join(ROOT_PATH, 'FMI_data/MD_data_partitions.csv')
community_path = os.path.join(ROOT_PATH, 'FMI_data/MD_data_communities.csv')

TAD_path = os.path.join(ROOT_PATH, 'FMI_data/Hi-C/MD_domains.bed')
PC_1_path = os.path.join(ROOT_PATH, 'FMI_data/Hi-C/MD_1.bw')
PC_2_path = os.path.join(ROOT_PATH, 'FMI_data/Hi-C/MD_2.bw')

In [11]:
G = nx.read_graphml(graph_path)

In [15]:
# Load the first communities file
communities1 = pd.read_csv(community_path)

# Transform communities into a dictionary where Gene field is the key and Community the value
gene_name_to_partition_mapping_sample_1 = {row['Gene']: row['Community'] for _, row in communities1.iterrows()}

In [19]:
# Load the first partitions file
partitions1 = pd.read_csv(partition_path)

# Transform partitions into a list of lists
partition_sample_1 = [list(map(int, entry.split(','))) for entry in partitions1['Content']]

In [20]:
partition_sample_1

[[2, 26147],
 [25784, 25867, 4],
 [26462, 6],
 [27488, 805, 27494, 808, 809, 810, 27497, 27499, 18, 27543, 27419, 27487],
 [27850, 21],
 [28165, 23],
 [28753, 25, 28766, 28654],
 [29792, 824, 27, 29837, 29838],
 [30209, 30],
 [32, 30067, 30071, 30073, 30074, 830, 31],
 [31110,
  31112,
  31113,
  31114,
  31115,
  31116,
  31117,
  31118,
  31119,
  31120,
  31121,
  31122,
  31059,
  31060,
  31057,
  31124,
  31128,
  31134,
  31135,
  31136,
  31137,
  34,
  35,
  33,
  30437,
  31138,
  31144,
  31145,
  31050],
 [31300, 31322, 31320, 31321, 42],
 [31682, 44, 31686],
 [51, 31791],
 [32368, 32377, 52],
 [32203, 32276, 53, 32231],
 [858, 59, 35567],
 [35656, 860, 61, 35652],
 [34736, 34729, 861, 62, 34733],
 [866, 867, 868, 35733, 67, 35735, 35740],
 [72, 35734],
 [36218, 36084, 76],
 [36549, 36554, 36528, 36529, 36502, 89, 36538, 36508],
 [96, 37329, 37270, 37334, 37279],
 [99, 100, 905, 37171, 37172, 37173, 37174, 37175, 37176, 37179, 37180],
 [37376, 37377, 37379, 101, 37350],
 [37443, 37367, 106, 37388, 37501],
 [114, 38366],
 [37764,
  37767,
  37768,
  37769,
  37770,
  38091,
  37772,
  37901,
  37902,
  37900,
  37904,
  37905,
  38097,
  37773,
  37908,
  37903,
  37898,
  37912,
  38117,
  37867,
  37868,
  37935,
  115,
  37814],
 [121, 122, 38726],
 [38561,
  38531,
  38563,
  38501,
  38564,
  38567,
  38504,
  38505,
  38570,
  38507,
  38571,
  38569,
  123],
 [128,
  130,
  131,
  924,
  39069,
  39070,
  39071,
  39072,
  39073,
  39074,
  39075,
  39076,
  39077,
  926,
  39079,
  39080,
  39081,
  930,
  39264,
  39417,
  925,
  39418,
  39099,
  39357,
  39361,
  39363,
  39364,
  39366,
  39422,
  39115,
  39246,
  38862,
  38868,
  39254,
  38870,
  39256,
  39257,
  39258,
  39259,
  39004,
  39260,
  39262,
  39263,
  38876,
  39265,
  39394,
  39267,
  39395,
  39396,
  39268,
  39266,
  38884,
  39401,
  38883,
  39407,
  38899,
  38900,
  39285,
  39161,
  39162,
  39419,
  126,
  127],
 [41124, 39943, 933, 135, 136, 41127],
 [141, 41694],
 [152, 954, 42558],
 [42884,
  42889,
  42890,
  42891,
  42892,
  42894,
  42895,
  42901,
  42902,
  153,
  155,
  156,
  42798,
  42801,
  42803,
  42804,
  43317,
  42806,
  42807,
  42810,
  42812,
  42813,
  959,
  960,
  961,
  43332,
  43096,
  43097,
  42840,
  42847,
  42850,
  42854,
  42855,
  42856,
  42857,
  42858,
  42859,
  42860,
  42861,
  42862,
  42863,
  42864,
  42865,
  42866,
  42868,
  42871,
  42877],
 [43584,
  43616,
  962,
  963,
  43613,
  43625,
  43615,
  43600,
  43576,
  43577,
  43580,
  157,
  158,
  43583],
 [43392,
  43393,
  43394,
  43395,
  43396,
  43397,
  43398,
  43399,
  43400,
  43401,
  43391,
  43402,
  966,
  159,
  161,
  162,
  163,
  165,
  43432,
  43387,
  43390,
  43647],
 [968, 170, 44094],
 [43749, 183],
 [184, 44109],
 [44457, 190],
 [44234, 191],
 [44836, 44837, 199, 200, 44621, 44574],
 [44544, 202, 44582, 991],
 [45237, 206],
 [1010, 46498, 211],
 [47296, 47300, 47301, 47302, 47304, 47280, 1015, 218, 47292, 47294, 47295],
 [47981, 223],
 [224, 48362, 48363, 48365, 48368, 48313, 48315, 1020],
 [1024,
  1025,
  1026,
  48409,
  48410,
  48411,
  48412,
  48797,
  48798,
  48799,
  48800,
  48801,
  48802,
  48803,
  48413,
  48805,
  48807,
  48562,
  48563,
  48564,
  48565,
  48566,
  48695,
  48697,
  48699,
  48700,
  48701,
  48702,
  48832,
  48836,
  48840,
  48841,
  48842,
  48854,
  48855,
  48856,
  48858,
  48859,
  48860,
  48861,
  48862,
  48863,
  48864,
  48865,
  48866,
  48483,
  48484,
  228,
  227,
  48867,
  230,
  231,
  48872,
  48871,
  229],
 [1030, 1031, 1032, 236, 49042, 49043, 49013, 49016, 49020],
 [48995,
  49027,
  48997,
  49001,
  48970,
  49003,
  48971,
  48972,
  48973,
  239,
  240,
  241,
  242,
  49015,
  48887],
 [1035, 49052, 1036, 247],
 [249, 49117, 49118],
 [49280, 49287, 49288, 265, 266],
 [1057, 49251, 49347, 49252, 49259, 267, 49295, 49307],
 [272, 270, 49326, 271],
 [50312, 50725, 276, 277],
 [50883, 279],
 [52160,
  52161,
  52162,
  52163,
  52164,
  52165,
  52166,
  291,
  292,
  52195,
  293,
  51950,
  1076,
  1078,
  1079,
  1080,
  51961,
  1082,
  52155,
  52156,
  1081,
  52158,
  52159],
 [52775,
  299,
  301,
  302,
  304,
  305,
  306,
  307,
  308,
  309,
  1090,
  1091,
  1092,
  1093,
  52810,
  52813,
  52814,
  52832,
  52834,
  52835,
  52837,
  52838,
  52839,
  52840,
  52841,
  52843,
  52844,
  52847,
  52849,
  52852,
  52853,
  52854,
  52856,
  52857,
  52858,
  52859,
  52861,
  52862,
  52864,
  52865,
  52866,
  52868,
  52869,
  52871,
  52872,
  52873,
  52875,
  52876,
  52877,
  52878,
  52880,
  52881,
  52882,
  52883,
  52884,
  52885,
  52886,
  52887,
  52888,
  52889,
  52890,
  52891,
  52892,
  52893,
  52894,
  52895,
  52896,
  52897,
  52898,
  52899,
  52900,
  52901,
  52919,
  52926,
  52927,
  52928,
  52933,
  52934,
  52937,
  52940,
  52941,
  52942,
  52954],
 [320,
  52993,
  53000,
  1097,
  1098,
  53002,
  53001,
  53005,
  53009,
  53010,
  53011,
  53012,
  53014,
  53017,
  53019,
  53020,
  53021,
  315,
  316,
  317,
  318,
  319],
 [53314, 325],
 [53216, 53193, 331, 332, 53231, 53237, 53239, 53240, 53242],
 [53740, 53741, 350, 53639],
 [1108,
  54165,
  54166,
  54167,
  53912,
  53913,
  1110,
  1109,
  54170,
  54168,
  54172,
  54173,
  54169,
  354,
  355,
  54120,
  54121],
 [54016,
  54017,
  54018,
  54019,
  54022,
  54045,
  53985,
  356,
  53993,
  53995,
  53997,
  53999,
  54000,
  54001,
  54002,
  54003,
  54004,
  54005,
  54006,
  54007,
  54008,
  54009,
  54010,
  54011,
  54012,
  54013,
  54014,
  54015],
 [54304, 362, 363],
 [369, 54595, 54588, 54597],
 [54480, 370],
 [54789,
  54790,
  54734,
  54799,
  54800,
  54801,
  54802,
  54803,
  54804,
  1121,
  54755,
  54833,
  372,
  373,
  54836,
  54773,
  54649,
  54782],
 [54930, 381],
 [385, 54863],
 [56122, 396, 56124],
 [56634, 399, 56209, 1142, 1143, 1144, 1146, 56154],
 [408, 59162],
 [1152,
  59520,
  1153,
  1154,
  59396,
  1155,
  59398,
  59457,
  59458,
  59459,
  59460,
  59461,
  59462,
  59463,
  59337,
  59276,
  59536,
  59410,
  59412,
  409,
  59421,
  59422,
  59425,
  59426,
  59427,
  59450,
  59451,
  59452,
  59454,
  59455],
 [59860, 421, 422],
 [63511, 63509, 63510, 423, 1164, 63519],
 [63664, 1169, 426, 427, 63789],
 [432, 64101],
 [436, 435, 66220],
 [66376, 443],
 [67363, 452, 67372, 67337, 67307, 1212, 67358],
 [67506, 1219, 454],
 [67652, 67598, 67495, 67678, 462],
 [67762, 476, 477],
 [478, 67871],
 [489, 68074, 68025, 68092, 68121],
 [68096,
  68097,
  68098,
  68099,
  68354,
  68101,
  68102,
  68103,
  68104,
  68234,
  68238,
  68239,
  68243,
  68250,
  68255,
  68257,
  68131,
  68260,
  68136,
  68138,
  68140,
  68141,
  68142,
  68144,
  68277,
  68150,
  68152,
  68153,
  68154,
  68219,
  68156,
  68157,
  68158,
  68159,
  68160,
  68161,
  68162,
  68221,
  68222,
  1229,
  1230,
  68350,
  1232,
  1233,
  1231,
  1235,
  1236,
  490,
  491,
  492,
  493,
  494,
  495,
  68091,
  68093,
  68094],
 [528, 68923, 1261],
 [69299, 535],
 [71528, 1281, 543],
 [547, 73438],
 [74064, 554, 1298],
 [74340, 74341, 74342, 74343, 74344, 74345, 74346, 74347, 74349, 558],
 [74442,
  74635,
  74636,
  74444,
  74445,
  74446,
  74448,
  74449,
  74452,
  74453,
  74644,
  74455,
  74646,
  74457,
  74648,
  74649,
  74650,
  1309,
  74651,
  74652,
  74656,
  74657,
  74653,
  563,
  565,
  566,
  74429],
 [74826,
  74828,
  74830,
  74831,
  74832,
  74833,
  74834,
  74835,
  1314,
  74804,
  74805,
  74806,
  74807,
  74808,
  74809,
  74810,
  571,
  572,
  573],
 [75168, 75169, 578, 579, 75173],
 [607, 1349, 606, 77103],
 [608, 77105, 77075, 77097, 77129, 602, 77023],
 [609, 77338, 77333, 1352, 77322, 77323, 77327],
 [77568,
  77569,
  77570,
  77571,
  77572,
  77573,
  77574,
  77576,
  77577,
  77579,
  77582,
  1356,
  611,
  612,
  77424,
  77425,
  77426,
  77427,
  77428,
  77429,
  77430,
  77431,
  77433,
  77434,
  77435,
  77436,
  77437,
  77439,
  77440,
  77441,
  77442,
  77444,
  77445,
  77446,
  77447,
  77448,
  77449,
  77450,
  77451,
  77452,
  77453,
  77454,
  77455,
  77458,
  77459,
  77460,
  77461,
  77463,
  77464,
  77465,
  77466,
  77467,
  77468,
  77478,
  77479,
  77481,
  77483,
  77484,
  77489,
  77492,
  77494,
  77496,
  77500,
  77513,
  77536,
  77538,
  77540,
  77546,
  77550,
  77552,
  77553,
  77558,
  77559,
  77561,
  77563,
  77564,
  77565,
  77566],
 [77841,
  77843,
  77844,
  77784,
  1372,
  77852,
  77854,
  77855,
  77856,
  77858,
  77859,
  77861,
  615,
  616,
  77865,
  618,
  77864,
  77867,
  621,
  77866,
  77863,
  77935],
 [78880,
  1386,
  1387,
  78892,
  78829,
  78830,
  78831,
  78832,
  630,
  631,
  632,
  633,
  635,
  78716,
  78717,
  78718],
 [79276, 642, 79220],
 [80000,
  80001,
  80002,
  80003,
  80004,
  645,
  80005,
  647,
  643,
  80009,
  80010,
  80011,
  80012,
  80013,
  80014,
  80015,
  80016,
  80018,
  80019,
  80030,
  79866,
  80296,
  646,
  80074,
  80077,
  80079,
  80080,
  80085,
  80220,
  80221,
  80229,
  1396,
  1398,
  1399,
  1400,
  1401,
  1402,
  1403,
  79999],
 [648, 80230],
 [80128,
  80130,
  80135,
  80136,
  649,
  80104,
  80105,
  80103,
  80110,
  80114,
  80149,
  1405],
 [668, 667, 80476],
 [672, 673, 80466, 671],
 [81001, 81011, 81012, 697, 81014, 81015, 81016, 81017, 81019, 81020],
 [81648, 1462, 81645, 702],
 [704, 82589, 703],
 [705, 706, 82580, 82294, 82296],
 [82806, 711, 82760, 82809, 82795, 82621],
 [83137,
  83138,
  83140,
  712,
  83025,
  83027,
  83029,
  83034,
  83036,
  83037,
  83038,
  83041,
  83049,
  82987,
  83052,
  82989,
  82988,
  83055,
  83056,
  83057,
  83122,
  82994,
  83058,
  83061,
  83062,
  83063,
  83128,
  83127,
  83132,
  83135],
 [83378, 83363, 83426, 83243, 719],
 [721, 83484],
 [722, 83518, 83519],
 [83537, 723, 83535],
 [83402, 83538, 725],
 [83841, 83842, 83844, 83848, 83835, 731],
 [84206, 84208, 84273, 84274, 84210, 84212, 84213, 84279, 84281, 84215, 735],
 [84080, 737, 84074, 84075, 84076, 84078],
 [752, 86054],
 [768,
  769,
  770,
  86784,
  86785,
  86788,
  86789,
  86918,
  86919,
  86792,
  86921,
  86794,
  86922,
  86796,
  86795,
  86790,
  86791,
  86920,
  86924,
  86834,
  86836,
  86841,
  86843,
  86844,
  86847,
  86848,
  86849,
  86850,
  86851,
  86852,
  86853,
  86773,
  86775,
  86776,
  1529,
  1530,
  86780,
  766,
  767],
 [774,
  87175,
  775,
  87177,
  87179,
  87180,
  87181,
  87166,
  87140,
  87141,
  87142,
  87143,
  87145,
  87164,
  1534,
  1535],
 [777, 87196, 1537],
 [25762, 25763, 30661, 25870, 25873, 25842, 794, 796, 797, 53502],
 [795, 25676, 26150, 26151],
 [27588,
  27591,
  27592,
  9,
  10,
  11,
  27597,
  15,
  26703,
  27604,
  26710,
  27548,
  26593,
  26594,
  803,
  804,
  26659,
  802,
  26661,
  26662,
  26663],
 [812, 27647],
 [28898, 28899, 820],
 [29643, 822, 823],
 [30242, 827],
 [29608, 828],
 [29914, 829],
 [31225, 834],
 [31267, 31269, 838],
 [847, 32063],
 [32410, 33211, 852],
 [34720,
  34721,
  34722,
  34723,
  34657,
  35593,
  35597,
  34637,
  34638,
  855,
  856,
  857],
 [35608, 862, 863],
 [81, 876, 36388, 36374],
 [36480,
  36481,
  36483,
  36486,
  36487,
  36413,
  36422,
  36471,
  36425,
  36429,
  77,
  36431,
  78,
  36434,
  83,
  84,
  86,
  875,
  877,
  878,
  879,
  36463,
  880,
  36465,
  882,
  36464,
  36461,
  36462,
  36470,
  36472,
  36473,
  36474],
 [884, 36620, 36614, 36615],
 [37122, 900, 37109],
 [37280, 37339, 908],
 [38096, 915, 37909, 38093],
 [922, 38511],
 [41432, 41321, 41379, 934],
 [144, 145, 41891, 942, 940, 41774, 943],
 [951, 42491, 42494, 42463],
 [43904, 43905, 974],
 [44033,
  44037,
  44041,
  43925,
  44054,
  44061,
  44062,
  44063,
  44065,
  44066,
  44067,
  44068,
  44069,
  44070,
  44072,
  44073,
  44074,
  44075,
  44076,
  44077,
  44078,
  44079,
  44080,
  44081,
  44082,
  44083,
  44085,
  181,
  43981,
  43982,
  975,
  976,
  43983,
  978,
  43984,
  980,
  43986,
  43988,
  43989,
  43990,
  43991,
  982,
  43993,
  43994,
  43996,
  43998,
  43999,
  44000,
  44001,
  44002,
  44003,
  44004,
  44005,
  44008,
  44009,
  44010,
  44012],
 [994, 995, 45647, 208, 45649, 45679, 45651, 45650, 45653, 45427],
 [45825,
  45826,
  45388,
  45391,
  45393,
  45394,
  209,
  210,
  45395,
  45857,
  45410,
  45858,
  996,
  997,
  998,
  1002],
 [45776, 45759, 45863, 1004, 1007],
 [45935, 45904, 45938, 1011, 1012, 46227, 45944, 217],
 [46634, 46646, 46647, 1016, 46619, 46791, 46635],
 [47328, 47362, 47363, 47332, 47365, 47333, 47367, 47368, 47369, 1017, 47327],
 [49137, 49100, 1038],
 [49154,
  259,
  260,
  261,
  262,
  264,
  49167,
  1040,
  49169,
  1039,
  1041,
  1042,
  1043,
  49174,
  1044,
  1045,
  49177,
  1046,
  1051,
  49179,
  1053,
  49182,
  49180,
  1054,
  1052,
  49185,
  49181,
  49187,
  49188,
  49189,
  49190,
  49191,
  49192,
  49194,
  49200,
  49209,
  49210,
  49211,
  49212,
  49213,
  49214,
  49217,
  49218,
  49220,
  49224,
  49226,
  49227,
  49229,
  49233,
  49234,
  49235,
  49236,
  49238,
  49239,
  49241,
  49244,
  49245,
  49255,
  49256,
  49257,
  49260,
  49265,
  49268,
  49269,
  49270,
  49274,
  49276,
  49298,
  49302,
  49304,
  49306,
  49311,
  49312,
  49313,
  1056,
  49144,
  251,
  254],
 [49361, 1059],
 [50104, 50196, 1061, 50223],
 [1062, 1063, 50377, 50378, 50410, 50379, 50382, 50351],
 [51321, 1067],
 [51328,
  51393,
  51329,
  51331,
  51395,
  51332,
  51334,
  51330,
  51336,
  51335,
  51460,
  51339,
  51333,
  51414,
  51415,
  51416,
  51417,
  51418,
  51419,
  282,
  51421,
  1069,
  1070,
  51391,
  51390,
  51326,
  51327],
 [51944, 1075],
 [1089, 52823],
 [52946, 52947, 1094],
 [53121,
  53133,
  53135,
  53137,
  53140,
  53141,
  53142,
  53143,
  53144,
  53145,
  53146,
  53147,
  53148,
  53149,
  53150,
  53151,
  53152,
  53162,
  53163,
  53035,
  53037,
  53036,
  53173,
  53176,
  313,
  53178,
  53179,
  1096,
  53103,
  53106,
  53114,
  53115],
 [53505,
  25602,
  53506,
  25606,
  25607,
  25862,
  25609,
  25610,
  25356,
  25868,
  25357,
  25362,
  25363,
  791,
  25112,
  25113,
  25626,
  25115,
  25627,
  25373,
  25628,
  25375,
  25631,
  25377,
  25378,
  25635,
  25116,
  25381,
  25382,
  25633,
  25130,
  25390,
  25135,
  25655,
  25658,
  25146,
  25151,
  25666,
  25410,
  25670,
  25671,
  25415,
  25165,
  25679,
  1104,
  25425,
  25168,
  25683,
  25684,
  25427,
  342,
  343,
  25177,
  25435,
  25436,
  25693,
  25697,
  25443,
  25700,
  25712,
  25200,
  25462,
  25213,
  25216,
  25479,
  25225,
  25744,
  25746,
  26006,
  25755,
  25501,
  25502,
  669,
  25508,
  25766,
  25254,
  25257,
  25514,
  25775,
  25520,
  25521,
  26295,
  25531,
  25538,
  25284,
  25797,
  25287,
  25289,
  25291,
  25292,
  25295,
  25297,
  25814,
  25302,
  25562,
  25568,
  25569,
  25313,
  25575,
  25319,
  25579,
  25324,
  53489,
  53490,
  53492,
  25333,
  53497,
  53498,
  25595,
  25597],
 [53771,
  53581,
  1105,
  1106,
  53530,
  53532,
  53533,
  53534,
  53535,
  53536,
  53540,
  53541,
  53542,
  53545,
  53546,
  53547,
  53548,
  53549,
  53551,
  53552,
  53553,
  53554,
  53555],
 [54192, 54193, 1111, 54190, 54191],
 [1112, 54383],
 [54455, 54612, 1119],
 [1120, 54428],
 [55046,
  55059,
  55061,
  55062,
  55063,
  55064,
  55069,
  55070,
  55074,
  55076,
  55081,
  54911,
  54845,
  54849,
  54851,
  54854,
  54855,
  54856,
  54857,
  54859,
  54866,
  54871,
  54872,
  54873,
  54874,
  54881,
  54883,
  1125,
  1126,
  1127,
  1128,
  54889,
  1130,
  1131,
  1134,
  54896,
  1136,
  54899,
  54900,
  54903,
  376,
  379,
  54910,
  383,
  384,
  54912,
  54914,
  54915,
  54916,
  54917,
  54918,
  391,
  54919,
  392,
  387,
  390,
  393,
  54925,
  54926,
  54928,
  386,
  54950,
  389,
  54955,
  54956,
  54957,
  54959,
  54960,
  54961,
  54963,
  54976,
  54977,
  54980,
  54981,
  54984,
  54990,
  54991,
  54992,
  54993,
  54994,
  54995,
  54997,
  54999,
  55000,
  55007,
  55037],
 [59296, 58914, 406, 58906, 1151, 58911],
 [61440,
  61441,
  61442,
  61443,
  61445,
  61446,
  61447,
  61448,
  1161,
  61450,
  61449,
  61452,
  61459,
  61464,
  61473,
  61474,
  61438,
  61439],
 [63824, 1170, 1171, 63822, 63823],
 [66243, 66244, 66245, 438, 1191, 1192, 1193],
 [66688,
  66689,
  66691,
  66692,
  66693,
  66694,
  66375,
  66696,
  66697,
  67213,
  66537,
  1196,
  1197,
  1198,
  1199,
  66685,
  66686,
  66687],
 [67425,
  451,
  67428,
  67431,
  67432,
  67433,
  67434,
  67435,
  67436,
  67437,
  67438,
  67441,
  1209],
 [67456, 67457, 1214],
 [1216,
  67616,
  67624,
  67634,
  67606,
  67608,
  67609,
  67610,
  67611,
  67612,
  67614,
  67615],
 [68066, 68052, 68056, 68057, 1226],
 [68381, 1238],
 [68492, 1245],
 [68672,
  68673,
  68674,
  515,
  68675,
  513,
  514,
  516,
  68618,
  68619,
  68620,
  68622,
  68623,
  68625,
  68694,
  68696,
  1246,
  1248,
  1249,
  1250,
  1251,
  1252,
  1253,
  68722,
  68659,
  68723,
  68725,
  68726,
  68727,
  68671],
 [68818, 68822, 1254],
 [1259, 68740, 68783],
 [69953, 1271, 69643, 69918, 69919],
 [70379, 70384, 70385, 70386, 70387, 539, 70429, 70430, 1279],
 [1282,
  1283,
  1292,
  1293,
  71441,
  71442,
  71444,
  71445,
  71446,
  71447,
  71448,
  71449,
  71450,
  71451,
  71452,
  71453,
  71454,
  71455,
  549,
  550,
  71463],
 [73857,
  73730,
  73733,
  1294,
  1295,
  1296,
  1297,
  73626,
  73768,
  73641,
  553,
  73770,
  552,
  73651,
  73782,
  73654,
  73788,
  73671,
  73673,
  73675,
  73676,
  73677,
  73678,
  73679,
  73680,
  73681,
  73684,
  73687,
  73691,
  73692,
  73693,
  73694,
  73695,
  73824,
  73825,
  73826,
  73696,
  73699,
  73829,
  73704,
  73707,
  73836,
  73709,
  73710,
  73970,
  73714,
  73716,
  73717,
  73718,
  73849,
  73722,
  73723,
  73853,
  73855],
 [74280, 1300, 74293],
 [74105, 74106, 74084, 1302],
 [74464, 74479, 74639, 1305, 74633, 1310, 1311],
 [1319,
  75016,
  1321,
  75018,
  75086,
  75087,
  75088,
  75090,
  75091,
  75092,
  75093,
  75094,
  75256,
  75257],
 [75264, 1324],
 [75602, 1334, 1335, 1336, 75723, 75724, 75725],
 [75593, 75582, 1337],
 [76480,
  76481,
  76482,
  76486,
  76499,
  76504,
  76505,
  76506,
  76507,
  601,
  76509,
  76510,
  76512,
  1342,
  76454,
  76468,
  76469,
  76470,
  76473,
  76474,
  76478],
 [1361, 1365, 77835, 77837, 78190],
 [78024,
  78032,
  78097,
  78098,
  78033,
  78100,
  78102,
  78039,
  1368,
  1369,
  1370,
  78110,
  78116,
  77929,
  77931,
  77932,
  78014],
 [78466, 78532, 78533, 78537, 78541, 78463, 624, 1373, 1374, 1375],
 [1376, 78276, 78277, 78279],
 [1379, 78260],
 [78628, 78261, 1382, 78566, 78638],
 [79172, 1389],
 [1392, 78894],
 [79296, 79279, 1393, 79282, 79284, 79285, 79286, 79287, 79288, 79289, 79290],
 [79776, 79808, 79809, 79842, 79840, 79814, 79815, 79820, 1394, 1395, 79774],
 [1408, 1409, 80323, 80333, 80334, 80337, 80338, 80344],
 [1410, 80325, 80319],
 [80387,
  80389,
  80390,
  80391,
  80397,
  80400,
  80401,
  80404,
  80417,
  80419,
  80425,
  80427,
  80428,
  80430,
  80431,
  80436,
  80443,
  80444,
  80446,
  80453,
  1407,
  1412,
  1413,
  1414,
  1415,
  1416,
  1417,
  650,
  1418,
  1419,
  1420,
  1422,
  1423,
  656,
  657,
  658,
  659,
  660,
  661,
  662,
  663,
  664,
  665,
  666,
  80304,
  80313,
  80314,
  80315,
  654,
  80092,
  655,
  80357,
  80358,
  80359,
  80361,
  80362,
  80363,
  80364,
  1421,
  80366,
  80368,
  80369,
  80371,
  80373,
  80376,
  1424,
  80383],
 [80642,
  80643,
  80644,
  80645,
  80646,
  80649,
  80652,
  80653,
  80654,
  80655,
  80657,
  80658,
  80659,
  80660,
  80661,
  80663,
  80664,
  80666,
  80668,
  80671,
  80678,
  80679,
  80680,
  80681,
  80683,
  80686,
  80688,
  80690,
  80691,
  80708,
  80710,
  80711,
  80712,
  80713,
  80714,
  80716,
  80718,
  80719,
  80720,
  80721,
  80722,
  80723,
  80724,
  80725,
  80726,
  80727,
  80728,
  80729,
  80730,
  1429,
  1430,
  1431,
  1432,
  1433,
  1434,
  1435,
  1436,
  676,
  677,
  678,
  679,
  680,
  681,
  682,

In [45]:
len(partition_sample_1)

3520

In [23]:
G.nodes["2"]

{'name': 'Atp6v1h_1',
 'colorType': 'green',
 'position': 'chr1:5083079-5083139',
 'partition': 0}

In [30]:
G.nodes["805"]

{'name': 'Snord87_1',
 'colorType': 'green',
 'position': 'chr1:9942533-9942593',
 'partition': 3}

In [29]:
list(G.neighbors("805"))

['27494']

In [99]:
TADs_df = pd.read_csv(TAD_path, sep='\t', header=None, names=['Chromosome', 'Start', 'End', "Id", "score", "strand", ".", ',', "color"])[['Chromosome', 'Start', 'End']]
TADs_df['Start'] = TADs_df['Start'].astype(int)
TADs_df['End'] = TADs_df['End'].astype(int)
TADs_df['Chromosome'] = 'chr' + TADs_df['Chromosome']

In [100]:
TADs_pr = pr.PyRanges(TADs_df)

/Users/wolffjoa/opt/miniconda3/envs/ega/lib/python3.10/site-packages/pyranges/methods/init.py:45: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return {k: v for k, v in df.groupby(grpby_key)}

In [101]:
TADs_pr

+--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int64)   | (int64)   |
|--------------+-----------+-----------|
| chr1         | 4775000   | 5300000   |
| chr1         | 5300000   | 6150000   |
| chr1         | 6150000   | 6875000   |
| chr1         | 6875000   | 8250000   |
| ...          | ...       | ...       |
| chrX         | 163150000 | 163525000 |
| chrX         | 163525000 | 166650000 |
| chrX         | 166650000 | 167250000 |
| chrX         | 167250000 | 168925000 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 3,721 rows and 3 columns from 20 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [ ]:
# make binsized genome
# count for each interaction its strength at start and end bin
# run hicexplorers TAD calling algorithm but for maximums instead of minimum
# two concaternated maxima should be the border of a TAD

In [120]:
import pyranges as pr

tad_interaction_threshold = 10
bin_size = 10000
start_community = []
end_community = []
community_list = []
all_positions = []
for community in partition_sample_1:
    community_position_list = []
    for node in community:
        chrom, positions = G.nodes[str(node)]['position'].split(":")
        start, end = positions.split("-")
        community_position_list.append([chrom, int(start), int(end)])

    if len(community_position_list) >= tad_interaction_threshold:
        all_positions.append(community_position_list)
        start_community.append(min(community_position_list))
        end_community.append(max(community_position_list))
        community_list.append([min(community_position_list)[0], min(community_position_list)[1], max(community_position_list)[2]])
    # max_position = max(community_position_list)
    # print(min_position, max_position)

    # BEGIN: Convert start_community and end_community into PyRanges objects
start_community_pr = pr.PyRanges(pd.DataFrame(start_community, columns=["Chromosome", "Start", "End"]))
end_community_pr = pr.PyRanges(pd.DataFrame(end_community, columns=["Chromosome", "Start", "End"]))
community_pr = pr.PyRanges(pd.DataFrame(community_list, columns=["Chromosome", "Start", "End"]))
    # END:

/Users/wolffjoa/opt/miniconda3/envs/ega/lib/python3.10/site-packages/pyranges/methods/init.py:45: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return {k: v for k, v in df.groupby(grpby_key)}
/Users/wolffjoa/opt/miniconda3/envs/ega/lib/python3.10/site-packages/pyranges/methods/init.py:45: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return {k: v for k, v in df.groupby(grpby_key)}
/Users/wolffjoa/opt/miniconda3/envs/ega/lib/python3.10/site-packages/pyranges/methods/init.py:45: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  return {k: v for k, v in df.groupby(grpby_key)}

In [119]:
all_positions[0]

[['chr1', 5083079, 5083139], ['chr1', 5884351, 5896685]]

In [95]:
start_community_pr

+--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int64)   | (int64)   |
|--------------+-----------+-----------|
| chr1         | 5083079   | 5083139   |
| chr1         | 4856126   | 4861117   |
| chr1         | 6487266   | 6487326   |
| chr1         | 9544824   | 9546917   |
| ...          | ...       | ...       |
| chrX         | 166673175 | 166673758 |
| chrX         | 166479637 | 166479697 |
| chrX         | 162899737 | 162902826 |
| chrX         | 161904763 | 161909945 |
| chrY         | 810378    | 814648    |
+--------------+-----------+-----------+
Unstranded PyRanges object has 3,520 rows and 3 columns from 21 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [109]:
community_pr

+--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int64)   | (int64)   |
|--------------+-----------+-----------|
| chr1         | 5083079   | 5896685   |
| chr1         | 4856126   | 6214674   |
| chr1         | 6487266   | 6859101   |
| chr1         | 9544824   | 10038227  |
| ...          | ...       | ...       |
| chrX         | 166673175 | 167209210 |
| chrX         | 166479637 | 167232295 |
| chrX         | 162899737 | 164076541 |
| chrX         | 161904763 | 162829415 |
| chrY         | 810378    | 1286619   |
+--------------+-----------+-----------+
Unstranded PyRanges object has 3,520 rows and 3 columns from 21 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [122]:
TADs_pr.join(community_pr).head(30)

+--------------+-----------+-----------+-----------+-----------+
| Chromosome   | Start     | End       | Start_b   | End_b     |
| (category)   | (int64)   | (int64)   | (int64)   | (int64)   |
|--------------+-----------+-----------+-----------+-----------|
| chr1         | 4775000   | 5300000   | 3004106   | 171559203 |
| chr1         | 4775000   | 5300000   | 4497360   | 88261254  |
| chr1         | 5300000   | 6150000   | 3004106   | 171559203 |
| chr1         | 5300000   | 6150000   | 4497360   | 88261254  |
| ...          | ...       | ...       | ...       | ...       |
| chr1         | 12300000  | 12850000  | 3004106   | 171559203 |
| chr1         | 12300000  | 12850000  | 4497360   | 88261254  |
| chr1         | 12850000  | 13150000  | 3004106   | 171559203 |
| chr1         | 12850000  | 13150000  | 4497360   | 88261254  |
+--------------+-----------+-----------+-----------+-----------+
Unstranded PyRanges object has 30 rows and 5 columns from 1 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [102]:
TAD_start_intersect = TADs_pr.intersect(start_community_pr)

In [105]:
TAD_end_intersect = TADs_pr.intersect(end_community_pr)

In [104]:
TAD_start_intersect

+--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int64)   | (int64)   |
|--------------+-----------+-----------|
| chr1         | 4856126   | 4861117   |
| chr1         | 5083079   | 5083139   |
| chr1         | 6487266   | 6487326   |
| chr1         | 7088934   | 7088994   |
| ...          | ...       | ...       |
| chrX         | 165326641 | 165327867 |
| chrX         | 166479637 | 166479697 |
| chrX         | 166673175 | 166673758 |
| chrX         | 168672142 | 168674517 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 3,525 rows and 3 columns from 20 chromosomes.
For printing, the PyRanges was sorted on Chromosome.

In [106]:
TAD_end_intersect

+--------------+-----------+-----------+
| Chromosome   | Start     | End       |
| (category)   | (int64)   | (int64)   |
|--------------+-----------+-----------|
| chr1         | 5884351   | 5896685   |
| chr1         | 5906194   | 5914460   |
| chr1         | 6214614   | 6214674   |
| chr1         | 6858080   | 6859101   |
| ...          | ...       | ...       |
| chrX         | 164373568 | 164373628 |
| chrX         | 166170424 | 166170484 |
| chrX         | 167209150 | 167209210 |
| chrX         | 167231015 | 167232295 |
+--------------+-----------+-----------+
Unstranded PyRanges object has 3,512 rows and 3 columns from 20 chromosomes.
For printing, the PyRanges was sorted on Chromosome.