In [2]:
import pyranges as pr
import pandas as pd

In [3]:
ROOT_PATH = '/Users/joachimwolff/data/epigenetic_graph_analyzer/raw_pc_hic/'
# path_interactions_E12_5_rep1 = ROOT_PATH + "phic/GSM6505214_Pinna_E12.5_CapHiC_Chicago_output_washU_text.txt.gz"
# path_interactions_E12_5_rep2 = ROOT_PATH + "phic/GSM6505215_Pinna_E12.5_CapHiC_3rdBioRep_Merged_cd_washU_text.txt.gz"

# path_interactions_E14_5_rep1 = ROOT_PATH + "phic/GSM6505216_Pinna_E14.5_CapHiC_Chicago_output_washU_text.txt.gz"
# path_interactions_E14_5_rep2 = ROOT_PATH + "phic/GSM6505217_Pinna_E14.5_CapHiC_3rdBioRep_cd_washU_text.txt.gz"

In [7]:
import os

folder_path = ROOT_PATH  # Replace with the actual folder path

files = [os.path.join(ROOT_PATH, f) for f in os.listdir(folder_path) if os.path.isfile(os.path.join(folder_path, f))]

In [8]:
def restoreRestrictionCutSites(list_of_pd_interactions_path):

    stacked_df = None
    for i, pd_interactions_path in enumerate(list_of_pd_interactions_path):
        pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
        data_frame = pd_interactions[[0,1,2,3,4,5]]       
        data_frame_forward = data_frame[[0,1,2]].rename(columns={0: 'Chromosome', 1: 'Start', 2: 'End'})
        data_frame_reverse = data_frame[[3,4,5]].rename(columns={3: 'Chromosome', 4: 'Start', 5: 'End'})
        if stacked_df is None:
            stacked_df = pd.concat([data_frame_forward, data_frame_reverse], axis=0, ignore_index=True)
        else:
            stacked_df = pd.concat([stacked_df, data_frame_forward, data_frame_reverse], axis=0, ignore_index=True)


    stacked_df.drop_duplicates(inplace=True, ignore_index=True)
    stacked_df.sort_values(by=['Chromosome', 'Start', 'End'], inplace=True)
    stacked_df.reset_index(inplace=True, drop=True)
    return stacked_df

In [9]:
restriction_cut_sited_df = restoreRestrictionCutSites(files)

/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')
/var/folders/05/b2bknm7d4w143by83wjfdmdw0000gn/T/ipykernel_5536/418732818.py:5: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pd_interactions = pd.read_table(pd_interactions_path, header=None, sep='\t|,', compression='gzip')

In [58]:
restriction_cut_sited_df.to_csv(os.path.join(ROOT_PATH + 'restriction_cut_sites.csv'), index=False, sep='\t')

In [10]:
chromosome_old = None
chromosome_new = None
start_old    = None
start_new    = None
end_old      = None 
end_new      = None
list_of_missing_restriction_cut_sites = []
for i, row in enumerate(restriction_cut_sited_df.iterrows()):
    chromosome_new = row[1]['Chromosome']
    start_new = row[1]['Start']
    end_new = row[1]['End']
    if chromosome_old == chromosome_new:
        start_new = row[1]['Start']
        end_new = row[1]['End']
        if end_old + 1 == start_new:
            chromosome_old = row[1]['Chromosome']
            start_old = row[1]['Start']
            end_old = row[1]['End']
            continue
        else:
            list_of_missing_restriction_cut_sites.append([chromosome_new, end_old+1, start_new-1])
            continue
    else:

       Chromosome     Start       End
0            chr1   3004106   3005820
1            chr1   3005821   3008316
2            chr1   3008317   3008894
3            chr1   3008895   3009813
4            chr1   3009814   3012423
...           ...       ...       ...
524331       chrY  86432294  86441076
524332       chrY  87307178  87308086
524333       chrY  88236833  88237614
524334       chrY  89979359  89979992
524335       chrY  90830873  90833836

[524336 rows x 3 columns]

In [21]:
pd_interactions_E12_5_rep1_forward = pd_interactions_E12_5_rep1[[0,1,2]].rename(columns={0: 'Chromosome', 1: 'Start', 2: 'End'})
pd_interactions_E12_5_rep1_reverse = pd_interactions_E12_5_rep1[[3,4,5]].rename(columns={3: 'Chromosome', 4: 'Start', 5: 'End'})

In [22]:
stacked_df = pd.concat([pd_interactions_E12_5_rep1_forward, pd_interactions_E12_5_rep1_reverse], axis=0, ignore_index=True)

In [24]:
stacked_df.drop_duplicates(inplace=True)

In [25]:
stacked_df

       Chromosome    Start      End
0            chr1  3100832  3102475
6            chr1  3676617  3679249
7            chr1  4359998  4362528
11           chr1  4495519  4498339
15           chr1  4521936  4530090
...           ...      ...      ...
275531       chrY  1025589  1026886
275532       chrY  1168639  1169738
275533       chrY  1013180  1014934
275534       chrY   939340   940729
275535       chrY  1099946  1100395

[92973 rows x 3 columns]

In [7]:
pd_interactions_E12_5_rep1

           0        1        2               3         4         5      6
0       chr1  3100832  3102475            chr1  88213919  88219911   6.23
1       chr1  3100832  3102475            chr1  88219912  88220831   6.23
2       chr1  3100832  3102475           chr17  23505926  23514823  13.64
3       chr1  3100832  3102475            chr9  16624619  16625522   5.74
4       chr1  3100832  3102475  chrUn_GL456239      7011      8069  11.43
...      ...      ...      ...             ...       ...       ...    ...
137763  chrY  1245110  1246846            chrY   1025589   1026886   6.65
137764  chrY  1245110  1246846            chrY   1168639   1169738   5.06
137765  chrY  1276141  1286958            chrY   1013180   1014934   5.57
137766  chrY  1304307  1309275            chrY    939340    940729   5.02
137767  chrY  1304307  1309275            chrY   1099946   1100395   5.27

[137768 rows x 7 columns]

In [1]:
restriction_cut_sited_df

NameError: name 'restriction_cut_sited_df' is not defined